import { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    app_title: 'Order Management System',
    sign_in: 'Sign In',
    sign_out: 'Sign Out',
    email: 'Email',
    password: 'Password',
    display_name: 'Display Name',
    role: 'Role',
    admin: 'Admin',
    customer: 'Customer',
    warehouse_manager: 'Warehouse Manager',
    factory_manager: 'Factory Manager',
    general_manager: 'General Manager',
    accountant: 'Accountant',
    dashboard: 'Dashboard',
    users: 'Users',
    branches: 'Branches',
    items: 'Items',
    orders: 'Orders',
    new_order: 'New Order',
    my_orders: 'My Orders',
    create_user: 'Create User',
    edit_user: 'Edit User',
    leave_blank_to_keep: 'leave blank to keep current',
    create_branch: 'Create Branch',
    edit_branch: 'Edit Branch',
    create_item: 'Create Item',
    edit_item: 'Edit Item',
    name: 'Name',
    location: 'Location',
    description: 'Description',
    category: 'Category',
    warehouse: 'Warehouse',
    factory: 'Factory',
    serial: 'Serial',
    quantity: 'Quantity',
    submit: 'Submit',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    actions: 'Actions',
    created_at: 'Created At',
    order_number: 'Order Number',
    branch: 'Branch',
    status: 'Status',
    pending: 'Pending',
    approved: 'Approved',
    completed: 'Completed',
    cancelled: 'Cancelled',
    select_branch: 'Select Branch',
    warehouse_items: 'Warehouse Items',
    factory_items: 'Factory Items',
    print: 'Print',
    monthly_summary: 'Monthly Summary',
    download_csv: 'Download CSV',
    month: 'Month',
    year: 'Year',
    total: 'Total',
    refresh: 'Refresh',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    redirecting: 'Redirecting...',
    confirm: 'Confirm',
    are_you_sure: 'Are you sure?',
    no_data: 'No data available',
    order_submitted: 'Order submitted successfully',
    order_created: 'Order created successfully',
    order_updated: 'Order updated successfully',
    order_deleted: 'Order deleted successfully',
    order_cancelled: 'Order cancelled successfully',
    cancel_order: 'Cancel Order',
    user_created: 'User created successfully',
    user_deleted: 'User deleted successfully',
    branch_created: 'Branch created successfully',
    branch_deleted: 'Branch deleted successfully',
    item_created: 'Item created successfully',
    item_deleted: 'Item deleted successfully',
    changes_saved: 'Changes saved successfully',
    view_details: 'View Details',
    close: 'Close',
    stock_level_required: 'Stock Level Required',
    stock_level_required_description: 'When checked, customers must provide current stock level when ordering this item',
    current_stock_level: 'Current Stock Level',
    required: 'Required',
    not_required: 'Not Required',
    stock_level_required_error: 'Please fill in the stock level for all required items',
    completed_orders_cannot_be_edited: 'Completed orders cannot be edited',
    po_approvals: 'PO Approvals',
    stock_alerts: 'Stock Level Alerts',
    current_stock: 'Current Stock',
    monthly_reports: 'Monthly Reports',
    manager: 'Manager',
    supplier: 'Supplier',
    price: 'Price',
    item: 'Item',
    material: 'Material',
    low: 'Low',
    raw_materials: 'Raw Materials',
    raw_material: 'Raw Material',
    supplier_management: 'Supplier Management',
    item_pricing_management: 'Item Pricing Management',
    customer_overview_by_branch: 'Customer Overview by Branch',
    current_warehouse_stock: 'Current Warehouse Stock',
    production_batches: 'Production Batches',
    raw_material_purchase_orders: 'Raw Material Purchase Orders',
    stock_adjustments: 'Stock Adjustments',
    adjustment_history: 'Adjustment History',
    low_stock_level_alerts: 'Low Stock Level Alerts',
    purchase_units: 'Purchase Units',
    production_date: 'Production Date',
    raw_materials_used_inputs: 'Raw Materials Used (Inputs)',
    stock_warning: 'Stock',
    adjustment_warning: 'Stock adjustments should only be used to correct discrepancies between actual physical stock and system records. All adjustments are logged with timestamps and reasons for audit purposes.',
    item_pricing_note: 'Make sure item prices are set in the Item Pricing tab for accurate cost calculations.',
    raw_material_management: 'Raw Material Management',
    outputs: 'Outputs',
    inputs: 'Inputs',
    alert: 'Alert',
    alerts: 'Alerts',
    all_stock_levels_normal: 'All Stock Levels Normal',
    no_items_below_minimum: 'No items are below minimum stock levels',
    minimum_level: 'Minimum Level',
    create_po: 'Create PO',
    contact: 'Contact',
    type: 'Type',
    unit: 'Unit',
    cost: 'Cost',
    minimum_stock: 'Minimum Stock',
    reorder_point: 'Reorder Point',
    lead_time_days: 'Lead Time (Days)',
    customer_orders: 'Customer Orders',
    purchase_orders: 'Purchase Orders',
    raw_material_pos: 'Raw Material POs',
    suppliers: 'Suppliers',
    add: 'Add',
    new: 'New',
    select: 'Select',
    choose: 'Choose',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    download: 'Download',
    upload: 'Upload',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    all: 'All',
    none: 'None',
    active: 'Active',
    inactive: 'Inactive',
    enabled: 'Enabled',
    disabled: 'Disabled',
    show: 'Show',
    hide: 'Hide',
    more: 'More',
    less: 'Less',
    details: 'Details',
    update: 'Update',
    remove: 'Remove',
    clear: 'Clear',
    reset: 'Reset',
    apply: 'Apply',
    approve: 'Approve',
    reject: 'Reject',
    reason: 'Reason',
    notes: 'Notes',
    comment: 'Comment',
    date: 'Date',
    time: 'Time',
    from: 'From',
    to: 'To',
    by: 'By',
    new_purchase_order: 'New Purchase Order',
    po_number: 'PO Number',
    no_purchase_orders_found: 'No purchase orders found. Create your first PO to get started',
    record_production: 'Record Production',
    batch_number: 'Batch Number',
    created: 'Created',
    no_production_batches_found: 'No production batches found. Record your first batch to get started',
    new_adjustment: 'New Adjustment',
    important: 'Important',
    adjustment_warning_full: 'Stock adjustments should only be used to correct discrepancies between actual physical stock and system records. All adjustments are logged with timestamps and reasons for audit purposes',
    difference: 'Difference',
    new_stock: 'New Stock',
    old_stock: 'Old Stock',
    item_material: 'Item/Material',
    no_adjustments_recorded: 'No adjustments recorded yet',
    factory_items_stock: 'Factory Items Stock',
    raw_materials_stock: 'Raw Materials Stock',
    no_factory_items_found: 'No factory items found',
    low_stock: 'Low Stock',
    no_stock_records_found: 'No stock records found',
    sale_units: 'Sale Units',
    warehouse_purchase_orders: 'Warehouse Purchase Orders',
    create_purchase_order: 'Create Purchase Order',
    vat_rate: 'VAT Rate',
    select_supplier: 'Select supplier',
    add_item: 'Add Item',
    no_items_added_yet: 'No items added yet',
  },
  ar: {
    app_title: 'نظام إدارة الطلبات',
    sign_in: 'تسجيل الدخول',
    sign_out: 'تسجيل الخروج',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    display_name: 'الاسم المعروض',
    role: 'الدور',
    admin: 'مسؤول',
    customer: 'عميل',
    warehouse_manager: 'مدير المستودع',
    factory_manager: 'مدير المصنع',
    general_manager: 'المدير العام',
    accountant: 'محاسب',
    dashboard: 'لوحة التحكم',
    users: 'المستخدمون',
    branches: 'الفروع',
    items: 'العناصر',
    orders: 'الطلبات',
    new_order: 'طلب جديد',
    my_orders: 'طلباتي',
    create_user: 'إنشاء مستخدم',
    edit_user: 'تعديل المستخدم',
    leave_blank_to_keep: 'اتركه فارغًا للإبقاء على الحالي',
    create_branch: 'إنشاء فرع',
    edit_branch: 'تعديل الفرع',
    create_item: 'إنشاء عنصر',
    edit_item: 'تعديل العنصر',
    name: 'الاسم',
    location: 'الموقع',
    description: 'الوصف',
    category: 'الفئة',
    warehouse: 'المستودع',
    factory: 'المصنع',
    serial: 'الرقم التسلسلي',
    quantity: 'الكمية',
    submit: 'إرسال',
    cancel: 'إلغاء',
    save: 'حفظ',
    edit: 'تعديل',
    delete: 'حذف',
    actions: 'الإجراءات',
    created_at: 'تاريخ الإنشاء',
    order_number: 'رقم الطلب',
    branch: 'الفرع',
    status: 'الحالة',
    pending: 'قيد الانتظار',
    approved: 'موافق عليه',
    completed: 'مكتمل',
    cancelled: 'ملغى',
    select_branch: 'اختر الفرع',
    warehouse_items: 'عناصر المستودع',
    factory_items: 'عناصر المصنع',
    print: 'طباعة',
    monthly_summary: 'الملخص الشهري',
    download_csv: 'تنزيل CSV',
    month: 'الشهر',
    year: 'السنة',
    total: 'المجموع',
    refresh: 'تحديث',
    loading: 'جاري التحميل...',
    error: 'خطأ',
    success: 'نجاح',
    redirecting: 'جاري إعادة التوجيه...',
    confirm: 'تأكيد',
    are_you_sure: 'هل أنت متأكد؟',
    no_data: 'لا توجد بيانات',
    order_submitted: 'تم إرسال الطلب بنجاح',
    order_created: 'تم إنشاء الطلب بنجاح',
    order_updated: 'تم تحديث الطلب بنجاح',
    order_deleted: 'تم حذف الطلب بنجاح',
    order_cancelled: 'تم إلغاء الطلب بنجاح',
    cancel_order: 'إلغاء الطلب',
    user_created: 'تم إنشاء المستخدم بنجاح',
    user_deleted: 'تم حذف المستخدم بنجاح',
    branch_created: 'تم إنشاء الفرع بنجاح',
    branch_deleted: 'تم حذف الفرع بنجاح',
    item_created: 'تم إنشاء العنصر بنجاح',
    item_deleted: 'تم حذف العنصر بنجاح',
    changes_saved: 'تم حفظ التغييرات بنجاح',
    view_details: 'عرض التفاصيل',
    close: 'إغلاق',
    stock_level_required: 'مستوى المخزون مطلوب',
    stock_level_required_description: 'عند التحديد، يجب على العملاء تقديم مستوى المخزون الحالي عند طلب هذا العنصر',
    current_stock_level: 'مستوى المخزون الحالي',
    required: 'مطلوب',
    not_required: 'غير مطلوب',
    stock_level_required_error: 'يرجى ملء مستوى المخزون لجميع العناصر المطلوبة',
    completed_orders_cannot_be_edited: 'لا يمكن تعديل الطلبات المكتملة',
    po_approvals: 'الموافقات على أوامر الشراء',
    stock_alerts: 'تنبيهات مستوى المخزون',
    current_stock: 'المخزون الحالي',
    monthly_reports: 'التقارير الشهرية',
    manager: 'مدير',
    supplier: 'المورد',
    price: 'السعر',
    item: 'العنصر',
    material: 'المادة',
    low: 'منخفض',
    raw_materials: 'المواد الخام',
    raw_material: 'مادة خام',
    supplier_management: 'إدارة الموردين',
    item_pricing_management: 'إدارة تسعير العناصر',
    customer_overview_by_branch: 'نظرة عامة على العملاء حسب الفرع',
    current_warehouse_stock: 'مخزون المستودع الحالي',
    production_batches: 'دفعات الإنتاج',
    raw_material_purchase_orders: 'أوامر شراء المواد الخام',
    stock_adjustments: 'تعديلات المخزون',
    adjustment_history: 'سجل التعديلات',
    low_stock_level_alerts: 'تنبيهات مستوى المخزون المنخفض',
    purchase_units: 'وحدات الشراء',
    production_date: 'تاريخ الإنتاج',
    raw_materials_used_inputs: 'المواد الخام المستخدمة (المدخلات)',
    stock_warning: 'المخزون',
    adjustment_warning: 'يجب استخدام تعديلات المخزون فقط لتصحيح التناقضات بين المخزون الفعلي وسجلات النظام. يتم تسجيل جميع التعديلات مع الطوابع الزمنية والأسباب لأغراض التدقيق.',
    item_pricing_note: 'تأكد من تعيين أسعار العناصر في علامة تبويب تسعير العناصر لحسابات التكلفة الدقيقة.',
    raw_material_management: 'إدارة المواد الخام',
    outputs: 'المخرجات',
    inputs: 'المدخلات',
    alert: 'تنبيه',
    alerts: 'تنبيهات',
    all_stock_levels_normal: 'جميع مستويات المخزون طبيعية',
    no_items_below_minimum: 'لا توجد عناصر تحت الحد الأدنى لمستوى المخزون',
    minimum_level: 'الحد الأدنى',
    create_po: 'إنشاء أمر شراء',
    contact: 'جهة الاتصال',
    type: 'النوع',
    unit: 'الوحدة',
    cost: 'التكلفة',
    minimum_stock: 'الحد الأدنى للمخزون',
    reorder_point: 'نقطة إعادة الطلب',
    lead_time_days: 'مدة التسليم (بالأيام)',
    customer_orders: 'طلبات العملاء',
    purchase_orders: 'أوامر الشراء',
    raw_material_pos: 'أوامر شراء المواد الخام',
    suppliers: 'الموردون',
    add: 'إضافة',
    new: 'جديد',
    select: 'اختر',
    choose: 'اختيار',
    search: 'بحث',
    filter: 'تصفية',
    export: 'تصدير',
    download: 'تنزيل',
    upload: 'رفع',
    back: 'رجوع',
    next: 'التالي',
    previous: 'السابق',
    all: 'الكل',
    none: 'لا شيء',
    active: 'نشط',
    inactive: 'غير نشط',
    enabled: 'مفعل',
    disabled: 'معطل',
    show: 'عرض',
    hide: 'إخفاء',
    more: 'المزيد',
    less: 'أقل',
    details: 'التفاصيل',
    update: 'تحديث',
    remove: 'إزالة',
    clear: 'مسح',
    reset: 'إعادة تعيين',
    apply: 'تطبيق',
    approve: 'موافقة',
    reject: 'رفض',
    reason: 'السبب',
    notes: 'ملاحظات',
    comment: 'تعليق',
    date: 'التاريخ',
    time: 'الوقت',
    from: 'من',
    to: 'إلى',
    by: 'بواسطة',
    new_purchase_order: 'أمر شراء جديد',
    po_number: 'رقم أمر الشراء',
    no_purchase_orders_found: 'لم يتم العثور على أوامر شراء. قم بإنشاء أول أمر شراء للبدء',
    record_production: 'تسجيل الإنتاج',
    batch_number: 'رقم الدفعة',
    created: 'تم الإنشاء',
    no_production_batches_found: 'لم يتم العثور على دفعات إنتاج. قم بتسجيل أول دفعة للبدء',
    new_adjustment: 'تعديل جديد',
    important: 'هام',
    adjustment_warning_full: 'يجب استخدام تعديلات المخزون فقط لتصحيح التناقضات بين المخزون الفعلي وسجلات النظام. يتم تسجيل جميع التعديلات مع الطوابع الزمنية والأسباب لأغراض التدقيق',
    difference: 'الفرق',
    new_stock: 'المخزون الجديد',
    old_stock: 'المخزون القديم',
    item_material: 'العنصر/المادة',
    no_adjustments_recorded: 'لم يتم تسجيل أي تعديلات بعد',
    factory_items_stock: 'مخزون عناصر المصنع',
    raw_materials_stock: 'مخزون المواد الخام',
    no_factory_items_found: 'لم يتم العثور على عناصر المصنع',
    low_stock: 'مخزون منخفض',
    no_stock_records_found: 'لم يتم العثور على سجلات مخزون',
    sale_units: 'وحدات البيع',
    warehouse_purchase_orders: 'أوامر شراء المستودع',
    create_purchase_order: 'إنشاء أمر شراء',
    vat_rate: 'نسبة ضريبة القيمة المضافة',
    select_supplier: 'اختر المورد',
    add_item: 'إضافة عنصر',
    no_items_added_yet: 'لم يتم إضافة عناصر بعد',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ar' : 'en');
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
