// Master data for SpicyMeal WMS.
// ITEMS: the official SpicyMeal item list (received 15/09/2026) — [code, English, Arabic, source, category].
// The order here is the order shown to branches. Codes are authoritative; do not invent SKUs.
// English names: light clean-up of spacing/typos only. W0088 had no English name — "Macaroni order bag" is a translation.

const ITEMS_VERSION = '2026-09-15b';

const ITEMS = [
  ["F0001", "Spicy Dinner Bag", "كيس دنر سبايسي", 'FACTORY', "Chicken"],
  ["F0002", "Regular Dinner Bag", "كيس دنر عادي", 'FACTORY', "Chicken"],
  ["F0003", "Spicy Slices Bag", "كيس شرائح حار", 'FACTORY', "Chicken"],
  ["F0004", "Regular Slices Bag", "كيس شرائح عادي", 'FACTORY', "Chicken"],
  ["F0005", "Spicy Nuggets Bag", "كيس نقتس حار", 'FACTORY', "Chicken"],
  ["F0006", "Regular Nuggets Bag", "كيس نقتس عادي", 'FACTORY', "Chicken"],
  ["F0007", "Spicy Fillet Bag", "كيس فيلية صدر حار", 'FACTORY', "Chicken"],
  ["F0008", "Regular Fillet Bag", "كيس فيلية صدر عادي", 'FACTORY', "Chicken"],
  ["F0009", "Spicy Zinger Bag", "كيس فيلية فخذ حار", 'FACTORY', "Chicken"],
  ["F0010", "Regular Zinger Bag", "كيس فيلية فخذ عادي", 'FACTORY', "Chicken"],
  ["F0011", "Wings Bag", "كيس اجنحة", 'FACTORY', "Chicken"],
  ["F0012", "Spicy Drumstick Bag", "كيس أفخاذ دجاج حار", 'FACTORY', "Chicken"],
  ["F0013", "Regular Drumstick Bag", "كيس أفخاذ دجاج عادي", 'FACTORY', "Chicken"],
  ["F0014", "Beef Burger", "برقر لحم", 'FACTORY', "Burgers, Seafood & Prepared"],
  ["F0015", "Chicken Burger", "برقر دجاج", 'FACTORY', "Burgers, Seafood & Prepared"],
  ["F0016", "Faheta Bag", "كيس فاهيتا", 'FACTORY', "Burgers, Seafood & Prepared"],
  ["F0017", "Shrimps Bag", "كيس روبيان", 'FACTORY', "Burgers, Seafood & Prepared"],
  ["F0036", "Macaroni béchamel", "مكرونة بشميل", 'FACTORY', "Burgers, Seafood & Prepared"],
  ["F0018", "Mutabbal", "متبل", 'FACTORY', "Dips & Salads"],
  ["F0019", "Hummus", "حمص", 'FACTORY', "Dips & Salads"],
  ["F0020", "Grape Leaves", "ورق عنب", 'FACTORY', "Dips & Salads"],
  ["F0021", "Coleslaw", "سلطة ملفوف", 'FACTORY', "Dips & Salads"],
  ["F0025", "Flour", "طحين", 'FACTORY', "Flour"],
  ["F0026", "Regular flour", "طحين عادي", 'FACTORY', "Flour"],
  ["F0027", "Employee Meal", "وجبة موظف", 'FACTORY', "Staff Meals"],
  ["F0028", "Cabbage", "ملفوف", 'FACTORY', "Vegetables"],
  ["F0029", "Lettuce", "خس", 'FACTORY', "Vegetables"],
  ["F0030", "Carrot", "جزر", 'FACTORY', "Vegetables"],
  ["F0031", "Tomatoes", "طماطم", 'FACTORY', "Vegetables"],
  ["F0032", "White Onion", "بصل ابيض", 'FACTORY', "Vegetables"],
  ["F0033", "Green Pepper", "فلفل اخضر", 'FACTORY', "Vegetables"],
  ["F0034", "Garlic", "ثوم", 'FACTORY', "Vegetables"],
  ["F0035", "Samurai Sauce", "صوص ساموراي", 'FACTORY', "Dips & Salads"],
  ["W0001", "French fries", "بطاطس عادي", 'WAREHOUSE', "Frozen Items"],
  ["W0002", "Potato wedges", "بطاطس ودجز", 'WAREHOUSE', "Frozen Items"],
  ["W0003", "Onion rings", "حلقات بصل", 'WAREHOUSE', "Frozen Items"],
  ["W0004", "Tortilla wraps", "خبز تويستر", 'WAREHOUSE', "Frozen Items"],
  ["W0005", "Mozzarella sticks", "اصابع جبن", 'WAREHOUSE', "Frozen Items"],
  ["W0006", "Jalapeno sticks", "هلابينو", 'WAREHOUSE', "Frozen Items"],
  ["W0007", "Chocolate cookies", "كوكيز بني", 'WAREHOUSE', "Frozen Items"],
  ["W0008", "White Cookies", "كوكيز ابيض", 'WAREHOUSE', "Frozen Items"],
  ["W0009", "Oil", "زيت نباتي للصاج", 'WAREHOUSE', "Dry Items & Cheese"],
  ["W0010", "Oil - machine", "زيت مكينة", 'WAREHOUSE', "Dry Items & Cheese"],
  ["W0011", "Salt", "ملح", 'WAREHOUSE', "Dry Items & Cheese"],
  ["W0012", "Ketchup", "كاتشب", 'WAREHOUSE', "Dry Items & Cheese"],
  ["W0013", "Sugar", "سكر", 'WAREHOUSE', "Dry Items & Cheese"],
  ["W0086", "Slice Cheese", "جبن شرائح", 'WAREHOUSE', "Dry Items & Cheese"],
  ["W0085", "Creamy Cheese", "جبن سائل", 'WAREHOUSE', "Dry Items & Cheese"],
  ["W0087", "Mayonnaise", "مايونيز", 'WAREHOUSE', "Dry Items & Cheese"],
  ["W0014", "Orange juice", "عصير برتقال", 'WAREHOUSE', "Beverages"],
  ["W0015", "Mango juice", "عصير مانجو", 'WAREHOUSE', "Beverages"],
  ["W0017", "Apple juice", "عصير تفاح", 'WAREHOUSE', "Beverages"],
  ["W0018", "Berry juice", "عصير توت", 'WAREHOUSE', "Beverages"],
  ["W0019", "Kinza Cola", "كينزا كولا", 'WAREHOUSE', "Beverages"],
  ["W0020", "Kinza Lemon", "كينزا ليمون", 'WAREHOUSE', "Beverages"],
  ["W0021", "Kinza Orange", "كينزا برتقال", 'WAREHOUSE', "Beverages"],
  ["W0022", "Kinza Cola Diet", "كينزا كولا دايت", 'WAREHOUSE', "Beverages"],
  ["W0023", "Kinza Lemon Diet", "كينزا ليمون دايت", 'WAREHOUSE', "Beverages"],
  ["W0024", "Kinza Citrus", "كينزا حمضيات", 'WAREHOUSE', "Beverages"],
  ["W0025", "Water", "علب ماء", 'WAREHOUSE', "Beverages"],
  ["W0026", "Trash bags", "أكياس نفايات", 'WAREHOUSE', "Bags"],
  ["W0027", "Plastic bags - X small", "كيس طلبات صغير جدا", 'WAREHOUSE', "Bags"],
  ["W0028", "Plastic bags - small", "كيس طلبات صغير", 'WAREHOUSE', "Bags"],
  ["W0029", "Plastic bags - medium", "كيس طلبات وسط", 'WAREHOUSE', "Bags"],
  ["W0030", "Plastic bags - large", "كيس طلبات كبير", 'WAREHOUSE', "Bags"],
  ["W0031", "White paper potato bags - small", "كيس ورق بطاطس صغير", 'WAREHOUSE', "Bags"],
  ["W0088", "Macaroni order bag", "كيس طلبات خاص للمكرونة", 'WAREHOUSE', "Bags"],
  ["W0032", "Paper plate - small", "صحن طاولة صغير", 'WAREHOUSE', "Paper Products"],
  ["W0033", "Paper plate - large", "صحن طاولة كبير", 'WAREHOUSE', "Paper Products"],
  ["W0034", "Twister paper", "ورق تويستر", 'WAREHOUSE', "Paper Products"],
  ["W0035", "Brown paper roll towel", "رول ورق بني", 'WAREHOUSE', "Paper Products"],
  ["W0036", "White paper roll towel", "رول ورق ابيض للزبائن", 'WAREHOUSE', "Paper Products"],
  ["W0037", "Thermal Paper Roll", "رول ورق الطابعات", 'WAREHOUSE', "Paper Products"],
  ["W0038", "Tissues", "منشاف طاولة", 'WAREHOUSE', "Paper Products"],
  ["W0039", "Tissues (City Mall)", "ورق نشاف ابيض مربعات", 'WAREHOUSE', "Paper Products"],
  ["W0040", "Garlic box", "علب ثوم", 'WAREHOUSE', "Canned / Packaging Items"],
  ["W0041", "Coleslaw box", "علب سلطة", 'WAREHOUSE', "Canned / Packaging Items"],
  ["W0042", "Sauce box", "علب صوص", 'WAREHOUSE', "Canned / Packaging Items"],
  ["W0043", "Dinner box", "علب دنر", 'WAREHOUSE', "Canned / Packaging Items"],
  ["W0044", "Slices box", "علب شرائح", 'WAREHOUSE', "Canned / Packaging Items"],
  ["W0045", "Fillet box", "علب صدر", 'WAREHOUSE', "Canned / Packaging Items"],
  ["W0046", "Zinger fillet box", "علب فخذ", 'WAREHOUSE', "Canned / Packaging Items"],
  ["W0047", "Kids meal box", "علب وجبة طفل", 'WAREHOUSE', "Canned / Packaging Items"],
  ["W0048", "Samurai meal box", "علب وجبة ساموراي", 'WAREHOUSE', "Canned / Packaging Items"],
  ["W0049", "Fries with Cheese Box", "علبة بطاطس بالجبن", 'WAREHOUSE', "Canned / Packaging Items"],
  ["W0050", "Shrimp Meal Box", "علب الروبيان", 'WAREHOUSE', "Canned / Packaging Items"],
  ["W0051", "Dynamite Meal Box", "علب ديناميت", 'WAREHOUSE', "Canned / Packaging Items"],
  ["W0052", "Gathering Meal Box", "علب وجبة اللمه", 'WAREHOUSE', "Canned / Packaging Items"],
  ["W0053", "Family Meal Box - Small", "علبة وجبة عائلية صغير", 'WAREHOUSE', "Canned / Packaging Items"],
  ["W0054", "Family Meal Box - Large", "علبة وجبة عائلية كبير", 'WAREHOUSE', "Canned / Packaging Items"],
  ["W0055", "Faheta box", "علب فاهيتا", 'WAREHOUSE', "Canned / Packaging Items"],
  ["W0056", "French fries packets", "كوب بطاطس", 'WAREHOUSE', "Canned / Packaging Items"],
  ["W0057", "Clorox", "كلوركس", 'WAREHOUSE', "Cleaning"],
  ["W0058", "Dishwashing liquid soap", "صابون غسيل الصحون", 'WAREHOUSE', "Cleaning"],
  ["W0059", "Handwashing soap", "صابون يد رغوة", 'WAREHOUSE', "Cleaning"],
  ["W0060", "Glass cleaner", "منظف زجاج", 'WAREHOUSE', "Cleaning"],
  ["W0061", "Rough sponge", "ليف خشنة", 'WAREHOUSE', "Cleaning"],
  ["W0062", "Grease remover", "مزيل للدهون", 'WAREHOUSE', "Cleaning"],
  ["W0063", "Broom", "مكنسة", 'WAREHOUSE', "Cleaning"],
  ["W0064", "Floor wiper", "مساحة", 'WAREHOUSE', "Cleaning"],
  ["W0065", "Wiper", "نب", 'WAREHOUSE', "Cleaning"],
  ["W0066", "Stick", "عصا", 'WAREHOUSE', "Cleaning"],
  ["W0067", "Plastic spoon - small", "ملعقة صغيرة", 'WAREHOUSE', "Plastics & Gloves"],
  ["W0068", "Plastic spoon - large", "ملعقة كبيرة", 'WAREHOUSE', "Plastics & Gloves"],
  ["W0069", "Plastic fork", "شوك", 'WAREHOUSE', "Plastics & Gloves"],
  ["W0070", "Rubber band", "سير فلوس", 'WAREHOUSE', "Plastics & Gloves"],
  ["W0071", "Machine filter", "فلتر مكينة", 'WAREHOUSE', "Plastics & Gloves"],
  ["W0072", "Kids toys", "هدايا الاطفال", 'WAREHOUSE', "Plastics & Gloves"],
  ["W0073", "Rubber gloves", "قفازات طحين", 'WAREHOUSE', "Plastics & Gloves"],
  ["W0074", "Medical gloves", "قفازات طبية", 'WAREHOUSE', "Plastics & Gloves"],
  ["W0075", "Plastic gloves", "قفازات بلاستك", 'WAREHOUSE', "Plastics & Gloves"],
  ["W0076", "Pins for stapler", "دبابيس للدباسة", 'WAREHOUSE', "Miscellaneous"],
  ["W0077", "Pen", "قلم كتابة جاف", 'WAREHOUSE', "Miscellaneous"],
  ["W0078", "Stapler", "دباسة", 'WAREHOUSE', "Miscellaneous"],
  ["W0079", "Lighter", "ولاعة فرن", 'WAREHOUSE', "Miscellaneous"],
  ["W0080", "Plastic aprons", "مريول", 'WAREHOUSE', "Miscellaneous"],
  ["W0081", "Cap", "قبعة", 'WAREHOUSE', "Miscellaneous"],
  ["W0082", "Face Masks", "كمامات", 'WAREHOUSE', "Miscellaneous"],
  ["W0083", "Online Orders Stickers", "رول ستيكرات التطبيقات", 'WAREHOUSE', "Miscellaneous"],
  ["W0084", "Date Stickers", "ستكر التاريخ", 'WAREHOUSE', "Miscellaneous"],
];

// Internal factory stock, not orderable by branches (raw material for cutting).
const FACTORY_RAW_ITEMS = [
  ['FR001', 'Whole chicken (raw)', 'دجاج كامل (خام)', 'FACTORY', 'Raw Materials'],
];

// Branch names. Codes B01..B17 assigned in this order.
const BRANCHES = [
  'Safwa', 'Awamiyah', 'Qudaih', 'Nasserah', 'Shubailiy', 'Murooj', 'Taroot', 'CityMall',
  'Majediyah', 'Jaroodiyah', 'Awjam', 'Qurtuba', 'Zuhoor', 'Malath', 'Dhahiyah', 'Jish', 'Alsaif',
];

// Placeholder default routes — the manager should edit these to match reality.
const DRIVERS = [
  { name: 'Driver 1', branches: ['Jish', 'Awjam', 'Safwa', 'Awamiyah', 'Qudaih', 'Jaroodiyah'] },
  { name: 'Driver 2', branches: ['Dhahiyah', 'Alsaif', 'Shubailiy', 'Murooj', 'Zuhoor', 'Qurtuba'] },
  { name: 'Driver 3', branches: ['Nasserah', 'Majediyah', 'Taroot', 'CityMall', 'Malath'] },
];

module.exports = { ITEMS_VERSION, ITEMS, FACTORY_RAW_ITEMS, BRANCHES, DRIVERS };
